# Generated by Django 3.2.4 on 2021-07-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.CharField(blank=True, default='placeholder.jpg', max_length=200, null=True, verbose_name='URL Imagen'),
        ),
    ]
